export var doencas = [
    "Sífilis",
    "Tricomoníase",
    "Transtorno de ansiedade",
    "Apendicite",
    "Dengue",
    "Crupe Viral",
    "Pneumonia",
    "Tuberculose",
    "Diabetes",
    "Síndrome de Cushing",
    "Hepatite viral",
    "Hiperplasia Adrenal Congênita",
    "Síndrome coronariana aguda",
    "Tromboembolismo pulmonar",
    "Lúpus eritematoso sistêmico",
    "Síndrome da mononucleose infecciosa",
    "Tireotoxicose",
    "Hemostasia",
    "Trombose",
    "Síndrome nefrótica"
]

// export const doencas = {
//     0:"Sífilis",
//     1:"Tricomoníase",
//     2:"Transtorno de ansiedade",
//     3:"Apendicite",
//     4:"Dengue",
//     5:"Crupe Viral",
//     6:"Pneumonia",
//     7:"Tuberculose",
//     8:"Diabetes",
//     9:"Síndrome de Cushing",
//     10:"Hepatite viral",
//     11:"Hiperplasia Adrenal Congênita",
//     12:"Síndrome coronariana aguda",
//     13:"Tromboembolismo pulmonar",
//     14:"Lúpus eritematoso sistêmico",
//     15:"Síndrome da mononucleose infecciosa",
//     16:"Tireotoxicose",
//     17:"Hemostasia",
//     18:"Trombose",
//     19:"Síndrome nefrótica"
// }